### PR TITLE
fix: Prevent onValueChange() from firing multiple times

### PR DESCRIPTION
**Pull request by fmaclen**
REF #46

### CODE REVIEW

**Comment by happysalada** [comment]
hey, thanks a lot for the change!
btw, there is a small mistake on the readme, the package is under `@canutin/svelte-currency-input` on npm , not just `svelte-currency-input`, if you are interested in correcting it.

**Comment by fmaclen** [comment]
I don't see a references in the `README.md` to the NPM package, maybe you meant `package.json`?

When I released it originally it was part of an organization account (hence `@canutin`) but I recently moved it to my personal account.

Renaming it would probably be problematic for the people already installed it, but I should update the URLs in the `package.json`.

**Comment by happysalada** [comment]
in Usage it says
`npm install svelte-currency-input --save`
I tried that with pnpm yesterday, and it didn't work.
doing `npm install @canutin/svelte-currency-input --save` however does work.

**Comment by fmaclen** [comment]
Ah gotcha, I missed that one. Thanks!

**Pull request merged**
